#define __has_attribute(x) 0
#define __has_c_attribute(x) 0
#define __has_cpp_attribute(x) 0
#define __has_builtin(x) 0
#define __has_include(x) 0
#define __has_include_next(x) 0
#define __has_embed(x) 0
#define __has_feature(x) 0
#define __has_extension(x) 0
#define _LP64 1
#define __C99_MACRO_WITH_VA_ARGS 1
#define __ELF__ 1
#define __LP64__ 1
#define __SIZEOF_DOUBLE__ 8
#define __SIZEOF_FLOAT__ 4
#define __SIZEOF_INT__ 4
#define __SIZEOF_LONG_DOUBLE__ 8
#define __SIZEOF_LONG_LONG__ 8
#define __SIZEOF_LONG__ 8
#define __SIZEOF_POINTER__ 8
#define __SIZEOF_PTRDIFF_T__ 8
#define __SIZEOF_SHORT__ 2
#define __SIZEOF_SIZE_T__ 8
#define __SIZE_TYPE__ unsigned long
#define __STDC_HOSTED__ 1
#define __STDC_NO_COMPLEX__ 1
#define __STDC_UTF_16__ 1
#define __STDC_UTF_32__ 1
#define __STDC_VERSION__ 201112L
#define __STDC_NO_VLA__ 1
#define __STDC__ 1
#define __USER_LABEL_PREFIX__
#define __amd64 1
#define __amd64__ 1
#define __gnu_linux__ 1
#define __CHAR_BIT__ 8
#define __SCHAR_MAX__ 127
#define __SHRT_MAX__ 32767
#define __INT_MAX__ 2147483647
#define __LONG_MAX__ 9223372036854775807L
#define __linux 1
#define __linux__ 1
#define __unix 1
#define __unix__ 1
#define __x86_64 1
#define __x86_64__ 1
#define __extension__
#define __GNUC__ 4
#define __GNUC_MINOR__ 2
#define __PRETTY_FUNCTION__ __FUNCTION__
#define linux 1
#define unix 1
#define __TINYC__ 1
#define __dcc__ 1
